/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PriceOracleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addPriceFeed"
      | "getPrice"
      | "getPriceUSD"
      | "getSupportedTokens"
      | "isPriceStale"
      | "latestPrices"
      | "owner"
      | "priceFeeds"
      | "supportedTokens"
      | "updatePrice"
      | "updatePrices"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "PriceFeedAdded" | "PriceUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addPriceFeed",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "getPrice", values: [string]): string;
  encodeFunctionData(functionFragment: "getPriceUSD", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getSupportedTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isPriceStale",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "latestPrices",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "priceFeeds", values: [string]): string;
  encodeFunctionData(
    functionFragment: "supportedTokens",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "updatePrice", values: [string]): string;
  encodeFunctionData(
    functionFragment: "updatePrices",
    values: [string[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "addPriceFeed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPriceUSD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSupportedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isPriceStale",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "latestPrices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "priceFeeds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePrices",
    data: BytesLike
  ): Result;
}

export namespace PriceFeedAddedEvent {
  export type InputTuple = [symbol: string, priceFeed: AddressLike];
  export type OutputTuple = [symbol: string, priceFeed: string];
  export interface OutputObject {
    symbol: string;
    priceFeed: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PriceUpdatedEvent {
  export type InputTuple = [
    symbol: string,
    price: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [symbol: string, price: bigint, timestamp: bigint];
  export interface OutputObject {
    symbol: string;
    price: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PriceOracle extends BaseContract {
  connect(runner?: ContractRunner | null): PriceOracle;
  waitForDeployment(): Promise<this>;

  interface: PriceOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addPriceFeed: TypedContractMethod<
    [symbol: string, priceFeedAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  getPrice: TypedContractMethod<
    [symbol: string],
    [
      [bigint, bigint, bigint] & {
        price: bigint;
        timestamp: bigint;
        decimals: bigint;
      }
    ],
    "view"
  >;

  getPriceUSD: TypedContractMethod<[symbol: string], [bigint], "view">;

  getSupportedTokens: TypedContractMethod<[], [string[]], "view">;

  isPriceStale: TypedContractMethod<[symbol: string], [boolean], "view">;

  latestPrices: TypedContractMethod<
    [arg0: string],
    [
      [bigint, bigint, bigint] & {
        price: bigint;
        timestamp: bigint;
        decimals: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  priceFeeds: TypedContractMethod<[arg0: string], [string], "view">;

  supportedTokens: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  updatePrice: TypedContractMethod<[symbol: string], [void], "nonpayable">;

  updatePrices: TypedContractMethod<[symbols: string[]], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addPriceFeed"
  ): TypedContractMethod<
    [symbol: string, priceFeedAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getPrice"
  ): TypedContractMethod<
    [symbol: string],
    [
      [bigint, bigint, bigint] & {
        price: bigint;
        timestamp: bigint;
        decimals: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPriceUSD"
  ): TypedContractMethod<[symbol: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSupportedTokens"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "isPriceStale"
  ): TypedContractMethod<[symbol: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "latestPrices"
  ): TypedContractMethod<
    [arg0: string],
    [
      [bigint, bigint, bigint] & {
        price: bigint;
        timestamp: bigint;
        decimals: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "priceFeeds"
  ): TypedContractMethod<[arg0: string], [string], "view">;
  getFunction(
    nameOrSignature: "supportedTokens"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "updatePrice"
  ): TypedContractMethod<[symbol: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updatePrices"
  ): TypedContractMethod<[symbols: string[]], [void], "nonpayable">;

  getEvent(
    key: "PriceFeedAdded"
  ): TypedContractEvent<
    PriceFeedAddedEvent.InputTuple,
    PriceFeedAddedEvent.OutputTuple,
    PriceFeedAddedEvent.OutputObject
  >;
  getEvent(
    key: "PriceUpdated"
  ): TypedContractEvent<
    PriceUpdatedEvent.InputTuple,
    PriceUpdatedEvent.OutputTuple,
    PriceUpdatedEvent.OutputObject
  >;

  filters: {
    "PriceFeedAdded(string,address)": TypedContractEvent<
      PriceFeedAddedEvent.InputTuple,
      PriceFeedAddedEvent.OutputTuple,
      PriceFeedAddedEvent.OutputObject
    >;
    PriceFeedAdded: TypedContractEvent<
      PriceFeedAddedEvent.InputTuple,
      PriceFeedAddedEvent.OutputTuple,
      PriceFeedAddedEvent.OutputObject
    >;

    "PriceUpdated(string,uint256,uint256)": TypedContractEvent<
      PriceUpdatedEvent.InputTuple,
      PriceUpdatedEvent.OutputTuple,
      PriceUpdatedEvent.OutputObject
    >;
    PriceUpdated: TypedContractEvent<
      PriceUpdatedEvent.InputTuple,
      PriceUpdatedEvent.OutputTuple,
      PriceUpdatedEvent.OutputObject
    >;
  };
}
